version: '3.8'

services:
  saya:
    container_name: saya
    build: .
    restart: always
    ports:
      - '1017:1017'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
      SAYA_HOST: 0.0.0.0
      SAYA_PORT: 1017
      SAYA_BASE_URI: /
      MIRAKURUN_HOST: mirakurun
      MIRAKURUN_PORT: 40772
