name: Docker

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches-ignore:
      - 'releases/**'

  release:
    types:
      - published

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: slashnephy/saya

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare image tag (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAG=dev" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      # 2FA を無効化する必要がある
      # https://github.com/peter-evans/dockerhub-description#action-inputs
      # - name: Update Docker Hub description
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ env.DOCKER_BASE_NAME }}
