name: Docker

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - dev

  release:
    types:
      - published

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: ghcr.io/slashnephy/saya

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare image tag (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAG=dev" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
          cache-from: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
          build-args: BUILDKIT_INLINE_CACHE=1
